log:
  exp_name: sculpture_clothes
render:
  base_theta: 90
guide:
  shape_path: editing/data/exp/sculpture2_1/mesh.obj
  initial_texture: editing/data/exp/sculpture2_1/albedo.png
  edit_text: "Red Coat"
  edit_model: 'Normal_Aware'
  input_point: "[[473,924],[613,707]]" #"[[865,1833],[1185,1825],[1501,1849],[1177,1721],[1185,1149]]"
  input_label: "[1,0]"
optim:
  seed: 25    